name: kriegspiel
version: '1.0'
license: BSD3
author:
  - Eric Zoerner <eric.zoerner@gmail.com>
maintainer:
  - Eric Zoerner <eric.zoerner@gmail.com>
copyright:
  - (c) 2018 Eric Zoerner
category: Game

data-dir: images

extra-source-files:
  - LICENSE

executables:
  kriegspiel:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    dependencies:
    - base
    - helm
    - hchesslib
    - directory
    - filepath
    - linear
    - optparse-applicative
    - containers
    - kriegspiel

library:
  source-dirs: src
  dependencies:
  - containers
  - directory
  - array
  - base
  - helm
  - linear
  - utility-ht
  - hchesslib
  - optparse-applicative

stability: experimental
